FROM sgtwilko/rpi-raspbian-opencv:latest-4.0.1
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade imutils
RUN pip3 install rpi-RFM69

ADD *.jpg /
ADD *.py /
CMD ["python3", "./locate-continuous.py"]

